name: smk-starter
version: '1.0'
summary: My summary
description: |
  A simple starter project for the SMK library.

grade: stable
confinement: strict
base: core18
apps:
  smk-starter:
    command: desktop-launch ${SNAP}/usr/local/bin/smk-starter
    plugs:
      - audio-playback
      - opengl
      - x11
parts:

  # Build cmake from source to get a recent version.
  cmake:
    source: https://github.com/Kitware/CMake
    source-type: git
    source-depth: 1
    plugin: cmake
    override-build: |
      mkdir -p build
      cd build
      cmake \
        -DCMAKE_INSTALL_PREFIX=$SNAPCRAFT_STAGE/cmake \
        $SNAPCRAFT_PART_SRC
      make -j 4
      make install

  smk-starter:
    after: [cmake]
    plugin: cmake
    source: https://github.com/ArthurSonzogni/smk-starter
    source-type: git
    source-depth: 1
    stage-packages:
      - libgl1-mesa-glx
      - libpulse0
    build-packages:
      - libglu-dev
      - libssl1.0-dev
      - libpulse-dev
      - xorg-dev
    override-build: |
      $SNAPCRAFT_STAGE/cmake/bin/cmake \
        -DCMAKE_INSTALL_PREFIX=$SNAPCRAFT_PART_INSTALL/usr/local \
        -DCMAKE_BUILD_TYPE=Release \
        $SNAPCRAFT_PART_SRC
      make -j 4
      make install

  desktop-glib-only:
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    build-packages:
    - libglib2.0-dev
    stage-packages:
    - libglib2.0-bin

passthrough:
  title: smk-starter
  license: MIT
